- name: Third task
  hosts: servera.lab.example.com
  gather_facts: no

  tasks:
    - name: Set up authorized keys
      loop: "{{ public_key_lists | map(attribute='public_keys') | flatten }}"
      ansible.posix.authorized_key:
        user: developer
        state: present
        key: "{{ lookup('file', item) }}"
