- name: Second task
  hosts: servera.lab.example.com
  gather_facts: no
  become: yes

  tasks:
    - name: Add users and put them in the right groups
      loop: "{{ my_users | subelements('my_groups') }}"
      ansible.builtin.user:
        name: "{{ item[0]['name'] }}"
        append: yes
        groups: "{{ item[1] }}"
        state: present
