- name: Second task
  hosts: servera.lab.example.com
  gather_facts: no
  become: yes

  tasks:
    - name: Add users and put them in the right groups
      loop: "{{ my_users | dict2items }}"
      ansible.builtin.debug:
        msg:
          - "name: {{ item['key'] }}"
          - "groups: {{ item['value']['my_groups'] }}"
    - name: test1
      loop: "{{ lookup('dict', my_users) }}"
      ansible.builtin.debug:
        msg:
          - "name: {{ item['key'] }}"
          - "groups: {{ item['value']['my_groups'] }}"
    - name: test 2
      loop: "{{ my_users | subelements('my_groups') }}"
      debug:
        msg:
          - "name: {{ item[0]['name'] }}"
          - "groups: {{ item[1] }}"

